### PR TITLE
fix: Fix stack overflows on indirect circular schemas (e.g. `Dog → Pet → Dog`) reported in kubb-labs/kubb#3172.

### LINKED ISSUE #68: @kubb/plugin-faker StackOverflow on recursive types
### What version of `kubb` is running?

4.37.4

### What kind of platform do you use?

Windows

### Your `kubb.config.ts` config file?

```typescript
import { defineConfig } from "@kubb/core";
import type { UserConfig } from "@kubb/core";
import type { Options as pluginOasOptions } from "@kubb/plugin-oas";
import { pluginOas } from "@kubb/plugin-oas";
import { pluginTs } from "@kubb/plugin-ts";
import { pluginFaker } from "@kubb/plugin-faker";

const pluginOptions = {
	contentType: "application/json",
	collisionDetection: true,
	group: {
		type: "tag",
		name: ({ group }) => `${group}Client`,
	},
} as const satisfies pluginOasOptions;

/**
 * @internal
 * @see https://kubb.dev/kubb/getting-started/configure
 */
export default defineConfig({
	root: ".",
	name: "bissantz-service",
	input: {
		path: "./input/openapi.json",
	},
	output: {
		path: "./gen-kubb",
		clean: true,
		defaultBanner: "full",
		format: false,
		lint: false,
	},

	plugins: [
		pluginOas({
			...pluginOptions,
			output: {
				path: "schema",
				banner: "/* eslint-disable */",
				barrelType: "named",
			},
		}),
		pluginTs({
			...pluginOptions,
			output: {
				path: "types",
				banner: "/* eslint-disable */",
				barrelType: "named",
			},
			paramsCasing: "camelcase",
			dateType: "string",
			unknownType: "unknown",
			emptySchemaType: "unknown",
			optionalType: "questionToken",
			arrayType: "array",
			integerType: "number",
		}),
		pluginFaker({
			...pluginOptions,
			output: {
				path: "faker",
				barrelType: "named",
			},
			dateType: "string",
			dateParser: "faker",
			unknownType: "unknown",
			emptySchemaType: "unknown",
			paramsCasing: "camelcase",
			regexGenerator: "faker",
			// Do not set otherwise it can not be overwritten in the tests
			seed: undefined,
			transformers: {
				name: (name) => name.replace(/^create/, "fake"),
			},
		}),
	],
} satisfies UserConfig);
```

### Swagger/OpenAPI file?

```bash
{
	"openapi": "3.1.0",
	"info": {
		"version": "1.0.0",
		"title": "Swagger Petstore",
		"license": {
			"name": "MIT",
			"url": "https://opensource.org/licenses/MIT"
		}
	},
	"servers": [
		{
			"url": "http://petstore.swagger.io/v1"
		}
	],
	"paths": {
		"/pets": {
			"get": {
				"summary": "List all pets",
				"operationId": "listPets",
				"tags": ["pets"],
				"parameters": [
					{
						"name": "limit",
						"in": "query",
						"description": "How many items to return at one time (max 100)",
						"required": false,
						"schema": {
							"type": "integer",
							"format": "int32"
						}
					}
				],
				"responses": {
					"200": {
						"description": "A paged array of pets",
						"headers": {
							"x-next": {
								"description": "A link to the next page of responses",
								"schema": {
									"type": "string"
								}
							}
						},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Pets"
								}
							}
						}
					},
					"default": {
						"description": "unexpected error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								}
							}
						}
					}
				}
			},
			"post": {
				"summary": "Create a pet",
				"operationId": "createPets",
				"tags": ["pets"],
				"responses": {
					"201": {
						"description": "Null response"
					},
					"default": {
						"description": "unexpected error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								}
							}
						}
					}
				}
			}
		},
		"/pets/{petId}": {
			"get": {
				"summary": "Info for a specific pet",
				"operationId": "showPetById",
				"tags": ["pets"],
				"parameters": [
					{
						"name": "petId",
						"in": "path",
						"required": true,
						"description": "The id of the pet to retrieve",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Expected response to a valid request",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Pet"
								}
							}
						}
					},
					"default": {
						"description": "unexpected error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"Pet": {
				"required": ["__typename"],
				"type": "object",
				"anyOf": [
					{
						"$ref": "#/components/schemas/Cat"
					},
					{
						"$ref": "#/components/schemas/Dog"
					}
				],
				"discriminator": {
					"propertyName": "__typename",
					"mapping": {
						"Cat": "#/components/schemas/Cat",
						"Dog": "#/components/schemas/Dog"
					}
				}
			},
			"Cat": {
				"type": "object",
				"required": ["id"],
				"properties": {
					"id": {
						"type": "integer",
						"format": "int64"
					},
					"__typename": {
						"enum": ["Cat"],
						"type": "string"
					},
					"archEnemy": {
						"oneOf": [
							{
								"type": "null"
							},
							{
								"$ref": "#/components/schemas/Pet"
							}
						]
					},
					"friends": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Pet"
						}
					}
				}
			},
			"Dog": {
				"type": "object",
				"required": ["id"],
				"properties": {
					"id": {
						"type": "integer",
						"format": "int64"
					},
					"__typename": {
						"enum": ["Dog"],
						"type": "string"
					},
					"archEnemy": {
						"oneOf": [
							{
								"type": "null"
							},
							{
								"$ref": "#/components/schemas/Pet"
							}
						]
					},
					"friends": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Pet"
						}
					}
				}
			},
			"Pets": {
				"type": "array",
				"items": {
					"$ref": "#/components/schemas/Pet"
				}
			},
			"Error": {
				"type": "object",
				"required": ["code", "message"],
				"properties": {
					"code": {
						"type": "integer",
						"format": "int32"
					},
					"message": {
						"type": "string"
					}
				}
			}
		}
	}
}
```

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```JSON
"@kubb/cli": "^4.37.3",
"@kubb/core": "^4.37.3",
"@kubb/plugin-client": "^4.37.3",
"@kubb/plugin-faker": "^4.37.3",
"@kubb/plugin-oas": "^4.37.3",
"@kubb/plugin-ts": "^4.37.3",
"@kubb/plugin-vue-query": "^4.37.3",
"@kubb/plugin-zod": "^4.37.3",
```

### What steps can reproduce the bug?

When having a schema which indirectly references itself (this is common when using polymorphism and child references) the generated zod types lead to an infinite recursion.

In the provided example there is a "base" DTO of Pet which can be either a Dog or a Cat. Both can reference other dogs/cats. The generated code looks like this:

`fakePet.ts`: 
```ts
import type { Pet } from "../types/Pet.ts";
import { faker } from "@faker-js/faker";
import { fakeCat } from "./fakeCat.ts";
import { fakeDog } from "./fakeDog.ts";

export function fakePet(data?: Partial<Pet>): Pet {
	return (
		data ||
		faker.helpers.arrayElement<any>([
			{ ...fakeCat(), ...{ __typename: "Cat" } },
			{ ...fakeDog(), ...{ __typename: "Dog" } },
		])
	);
}
```

`fakeCat.ts`
```ts
import type { Cat } from "../types/Cat.ts";
import { faker } from "@faker-js/faker";
import { fakePet } from "./fakePet.ts";

export function fakeCat(data?: Partial<Cat>): Cat {
	return {
		...{
			id: faker.number.int(),
			__typename: faker.helpers.arrayElement<NonNullable<Cat>["__typename"]>([
				"Cat",
			]),
			archEnemy: faker.helpers.arrayElement<any>([null, fakePet()]),
			friends: faker.helpers.multiple(() => fakePet()),
		},
		...(data || {}),
	};
}
```

`fakeDog.ts`:
```ts
import type { Dog } from "../types/Dog.ts";
import { faker } from "@faker-js/faker";
import { fakePet } from "./fakePet.ts";

export function fakeDog(data?: Partial<Dog>): Dog {
	return {
		...{
			id: faker.number.int(),
			__typename: faker.helpers.arrayElement<NonNullable<Dog>["__typename"]>([
				"Dog",
			]),
			archEnemy: faker.helpers.arrayElement<any>([null, fakePet()]),
			friends: faker.helpers.multiple(() => fakePet()),
		},
		...(data || {}),
	};
}
```

When you call `fakeDog()` the `friends` will try to create a `fakePet` which might be a `fakeDog` again and there is the recursion.

### How often does this bug happen?

Every time

### What is the expected behavior?

In generel no StackOverflow error should be thrown.

I would expect that these cases are either handled like the direct recursion where if possible `undefined`/`null` is used instead of creating a fake instance.

Or that it is somehow possible to provide data which is able to stop the recursion since its most likely hard to detect these loops in general.
I would probably fix this using lazy getters so that they can be overwritten before they execute and create the fake instance. The file would then look something like this:

```ts
import type { Dog } from "../types/Dog.ts";
import { faker } from "@faker-js/faker";
import { fakePet } from "./fakePet.ts";

export function fakeDog(data?: Partial<Dog>): Dog {
	return {
		...{
			id: faker.number.int(),
			__typename: faker.helpers.arrayElement<NonNullable<Dog>["__typename"]>([
				"Dog",
			]),
			get archEnemy() {
				return faker.helpers.arrayElement<any>([null, fakePet()]);
			},
			get friends() {
				return faker.helpers.multiple(() => fakePet());
			},
			...(data || {}),
		},
	};
}
```

This way if `archEnemy` and `friends` is provided faker never tries to create any objects.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stijnvanhulle**

### CODE REVIEW

File: packages/plugin-faker/src/generators/__snapshots__/catCycle/cat.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+ * Do not edit manually.
+ */
+
+import type { Cat } from './types/Cat'
+import { faker } from '@faker-js/faker'
+
+export function cat(data?: Partial<Cat>): Cat {
+  const result: Cat = {
+    id: faker.number.int(),
+    get archEnemy() {
```
Comment (DesselBane) [inline packages/plugin-faker/src/generators/__snapshots__/catCycle/cat.ts:12]: @stijnvanhulle Using this solution the order of faker methods is now determined by when and how often the properties are called (as far as I can see), which leads to unstable test data. Are there any tests which validate that the generated props are stable? Like this:

```
const myCat = cat()
const first = myCat.archEnemy
const second = myCat.archEnemy

expect(first).toBe(second)
```

Or in other words is this an issue or is this fixed/prohibited somewhere else?

Comment (stijnvanhulle) [reply packages/plugin-faker/src/generators/__snapshots__/catCycle/cat.ts:12]: @DesselBane hmm not sure how else we can do this without having loop issues. Any suggestions on how you would see this?

Comment (DesselBane) [reply packages/plugin-faker/src/generators/__snapshots__/catCycle/cat.ts:12]:
```ts
export function cat(data?: Partial<Cat>): Cat {
  const result: Cat = {
    id: faker.number.int(),
    get archEnemy() {Expand commentComment on line R12
      return faker.helpers.arrayElement<any>([null, pet()])
    },
    get friends() {
      return faker.helpers.multiple(() => pet())
    },
  }
  if (data) Object.assign(result, data)
  return {
    ...result
  }
}
```
Would resolve the issue but require that the user overwrites the properties. If this should never be an issue then it would probably make the most sense that for arrays an empty array is returned and for direct object references we could use the same mechanism as for direct loops `return undefined as any` (or better `return undefined as never`)
